; GCode generated by skeinforge - on-signal config 2011
G28                               ;go home
G92 E0                          ;set extruder home
G1 E20 ; extrude some
G92 E0                          ;set extruder home
M104 S250.0                   ;set temperature to 250.0
