; GCode generated by skeinforge - on-signal config 2011
G28                               ;go home
M104 S250.0                   ;set temperature to 250.0

G90 ; absolute positioning
G1 Z2 F30		; a few mm up

G92 E0                          ;set extruder home
G1 F1000 E100 ; extrude some
G92 E0                          ;set extruder home

